<?php
$usedCars = [
    [
        "id" => 1,
        "brand" => 'fiat',
        "model" => 'punto',
        "fuel" => 'gas, diesel or GPL',
        "year" => 2015,
        "displacement" => 1368,
        "horse_power" => 70,
        "Kilometers" => 92750,
        "color" => 'black',
        "transmission" => 'automatic',
        "car_body" => 'utilitarian',
        "locality" => 'firenze',
        "accessories" => 'Window lift switch for car, Velcro carpet car mats',
        "car_porter" => 5,
        "traction" => 'front-wheel drive',
        "price" => 9000.50,
        "photo" => 'https://cdn.shortpixel.ai/spai/w_1000+q_lossy+ret_img+to_webp/https://www.motorimagazine.it/wp-content/uploads/2018/08/fiat-punto.jpg',
    ],
    [
        "id" => 2,
        "brand" => 'audi',
        "model" => 'R8',
        "fuel" => 'gas or diesel',
        "year" => 2005,
        "displacement" => 1800,
        "horse_power" => 120,
        "Kilometers" => 42000,
        "color" => '',
        "transmission" => 'manual',
        "car_body" => '',
        "locality" => '',
        "accessories" => '',
        "car_porter" => 3,
        "traction" => 'front-wheel drive',
        "price" => 2850.000,
        "photo" => 'https://cdn.motor1.com/images/mgl/BqPZM/s3/2021-audi-r8-rwd-panther-edition.jpg',
    ],
    [
        "id" => 3,
        "brand" => 'fiat',
        "model" => 'panda',
        "fuel" => 'gas, diesel or GPL',
        "year" => 2008,
        "displacement" => 1249,
        "horse_power" => 55,
        "Kilometers" => 82100,
        "color" => 'red',
        "transmission" => 'manual',
        "car_body" => 'utilitarian',
        "locality" => '',
        "accessories" => 'Window lift switch for car',
        "car_porter" => 5,
        "traction" => 'front-wheel drive',
        "price" => 7500.00,
        "photo" => 'https://www.motorinotizie.it/wp-content/uploads/2020/02/panda1-1210x642.jpg',
    ],
    [
        "id" => 4,
        "brand" => 'peugeot',
        "model" => 'xmas',
        "fuel" => 'diesel or GPL',
        "year" => 1979,
        "displacement" => 600,
        "horse_power" => 24,
        "Kilometers" => 120350,
        "color" => '',
        "transmission" => 'manual',
        "car_body" => '',
        "locality" => 'genova',
        "accessories" => '',
        "car_porter" => 5,
        "traction" => 'front-wheel drive',
        "price" => 1500.00,
        "photo" => 'https://pbs.twimg.com/media/DvMW8eZXQAAAeSJ?format=png&name=large',
    ],
    [
        "id" => 5,
        "brand" => 'BMW',
        "model" => 'serie 5',
        "fuel" => 'gas, diesel or GPL',
        "year" => 2008,
        "displacement" => 1249,
        "horse_power" => 55,
        "Kilometers" => 82100,
        "color" => 'red',
        "transmission" => 'manual',
        "car_body" => 'utilitarian',
        "locality" => '',
        "accessories" => 'Window lift switch for car',
        "car_porter" => 5,
        "traction" => 'front-wheel drive',
        "price" => 7500.00,
        "photo" => 'https://www.motorinotizie.it/wp-content/uploads/2020/02/panda1-1210x642.jpg',
    ],
    [
        "id" => 6,
        "brand" => 'BMW',
        "model" => 'serie 4',
        "fuel" => 'gas, diesel or GPL',
        "year" => 2000,
        "displacement" => 1569,
        "horse_power" => 87,
        "Kilometers" => 71000,
        "color" => '',
        "transmission" => 'manual',
        "car_body" => '',
        "locality" => '',
        "accessories" => '',
        "car_porter" => 5,
        "traction" => 'front-wheel drive',
        "price" => 1850.000,
        "photo" => 'https://www.nanninember.it/bmw-serie-1-con-why-buy-evo~7~8~429~429.jpeg',
    ],
    [
        "id" => 7,
        "brand" => 'Disney',
        "model" => 'pippomobile',
        "fuel" => 'gas, diesel or GPL',
        "year" => 2020,
        "displacement" => 9999,
        "horse_power" => 999,
        "Kilometers" => 9,
        "color" => 'green',
        "transmission" => 'manual',
        "car_body" => 'utilitarian',
        "locality" => '',
        "accessories" => '',
        "car_porter" => 5,
        "traction" => 'front-wheel drive',
        "price" => 7500.00,
        "photo" => '',
    ],
];
?>